model:
  class_name: model.PanoWorldLRM

  patch_factor: 2
  dim1: 256
  dim2: 512
  dim3: 1024
  num_register_tokens: 4
  head_dim: 64
  inter_multi: 4
  qk_norm: true
  stage1_nlayer: 2
  stage2_nlayer: 4
  stage3_nlayer: 8
  patch_size: 2
  in_channels: 12
  output_gs: true

  gaussians:
    sh_degree: 1
    opacity_degree: 2
    near_plane: 0.01
    far_plane: 1000000.0
    scale_bias: -6.9
    scale_max: -1.2
    opacity_bias: 1.0
    align_to_pixel: true
    max_dist: 15.0
    min_dist: 0.1

data:
  root_data_dir: "/mnt/xyz_data_tj/user/jiajinrang001/panoworld_hug/RealSee3D_eval_data"
  data_path: "data_realsee3D/realsee3D_eval_8views.txt"
  # data_path: "data_realsee3D/realsee3D_eval_12views.txt"
  square_crop: true # Whether to crop perspective images to a square before resizing
  resize_h: 512
  resize_h_pano: 512
  viewpoint_max_view: 12
  filter_top_down: false # set true to ignore the pano image top 1/5 and down 1/5

training:
  # Selects the resolution-specific attention layout used by the checkpoint.
  train_stage: 1 # 1: 1024x512, 2: 2048x1024

inference:
  dataset_name: dataset.Dataset
  amp_dtype: bf16
  use_amp: true  
  batch_size_per_gpu: 1
  num_threads: 8
  num_workers: 4
  prefetch_factor: 4  
  use_tf32: true
  ckpt_path: /mnt/xyz_data_tj/user/jiajinrang001/MVP_exp/id16_best_512_patch_whole_room_kujiale_RealSee3D/experiments_20260328_id16_512/checkpoints/mvp_stage1/ckpt_0000000000096000.pt
  out_dir: ./inference_result/inference_1024_512_8views